let dataStructure = [
    {
      day:"1",
      content:"./assets/jul.jpg"
    },
    {
      day:"2",
      content:"./assets/jul.jpg"
    },
    {
      day:"3",
      content:"./assets/jul.jpg"
    },
    {
      day:"4",
      content:"./assets/jul.jpg"
    },
    {
      day:"5",
      content:"./assets/jul.jpg"
    },
    {
      day:"6",
      content:"./assets/jul.jpg"
    },
    {
      day:"7",
      content:"./assets/jul.jpg"
    },
    {
      day:"8",
      content:"./assets/jul.jpg"
    },
    {
      day:"9",
      content:"./assets/jul.jpg"
    },
  ] 
  